DELETE https://silent-haze-5202.fly.dev/api/persons/3

###
POST https://silent-haze-5202.fly.dev/api/persons
content-type: application/json

{
    "name": "sample",
    "number": "32132131231232"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "sample",
    "number": "32132131231232"
}